-- 코드를 입력하세요
SELECT DATE_FORMAT(ons.SALES_DATE,'%Y-%m-%d') as SALES_DATE , ons.PRODUCT_ID, ons.USER_ID, ons.SALES_AMOUNT
FROM ONLINE_SALE ons
WHERE ons.SALES_DATE LIKE '2022-03%' 

UNION ALL

select DATE_FORMAT(ofs.SALES_DATE,'%Y-%m-%d') as SALES_DATE, ofs.PRODUCT_ID, NULL AS USER_ID, ofs.SALES_AMOUNT
from OFFLINE_SALE  ofs
where ofs.SALES_DATE LIKE '2022-03%'

ORDER BY 1 ASC, 2 ASC, 3 ASC
;