-- 코드를 입력하세요
SELECT rr.REST_ID, ri.REST_NAME, ri.FOOD_TYPE, ri.FAVORITES, ri.ADDRESS, ROUND(AVG(REVIEW_SCORE),2) AS SCORE
FROM REST_INFO ri
JOIN REST_REVIEW rr ON ri.REST_ID = rr.REST_ID
WHERE ri.ADDRESS regexp '서울시|서울특별시'
GROUP BY rr.REST_ID
ORDER BY 6 DESC, 4 DESC
;